package dao;

import model.PostTable;
import model.PostTableExample;
import model.PostTableWithBLOBs;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PostTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int countByExample(PostTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int deleteByExample(PostTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int insert(PostTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int insertSelective(PostTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    List<PostTableWithBLOBs> selectByExampleWithBLOBs(PostTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    List<PostTable> selectByExample(PostTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    PostTableWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") PostTableWithBLOBs record, @Param("example") PostTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") PostTableWithBLOBs record, @Param("example") PostTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExample(@Param("record") PostTable record, @Param("example") PostTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByPrimaryKeySelective(PostTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(PostTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table post_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByPrimaryKey(PostTable record);

    int updateFloor(PostTable record);
}