package dao;

import model.ReplyTable;
import model.ReplyTableExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ReplyTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int countByExample(ReplyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int deleteByExample(ReplyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int insert(ReplyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int insertSelective(ReplyTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    List<ReplyTable> selectByExampleWithBLOBs(ReplyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    List<ReplyTable> selectByExample(ReplyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") ReplyTable record, @Param("example") ReplyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ReplyTable record, @Param("example") ReplyTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reply_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExample(@Param("record") ReplyTable record, @Param("example") ReplyTableExample example);
}