package dao;

import model.UserTable;
import model.UserTableExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int countByExample(UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int deleteByExample(UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int insert(UserTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int insertSelective(UserTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    List<UserTable> selectByExample(UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserTable record, @Param("example") UserTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_table
     *
     * @mbggenerated Tue May 01 19:28:10 CST 2018
     */
    int updateByExample(@Param("record") UserTable record, @Param("example") UserTableExample example);

    int updateByEmail(@Param("record") UserTable record);
}