package model;

import java.util.Date;

public class PostTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_table.id
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_table.username
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_table.replayNumber
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private Integer replaynumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_table.time
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_table.id
     *
     * @return the value of post_table.id
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_table.id
     *
     * @param id the value for post_table.id
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_table.username
     *
     * @return the value of post_table.username
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_table.username
     *
     * @param username the value for post_table.username
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_table.replayNumber
     *
     * @return the value of post_table.replayNumber
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public Integer getReplaynumber() {
        return replaynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_table.replayNumber
     *
     * @param replaynumber the value for post_table.replayNumber
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setReplaynumber(Integer replaynumber) {
        this.replaynumber = replaynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_table.time
     *
     * @return the value of post_table.time
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_table.time
     *
     * @param time the value for post_table.time
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }
}