package model;

public class PostTableWithBLOBs extends PostTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_table.title
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post_table.content
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_table.title
     *
     * @return the value of post_table.title
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_table.title
     *
     * @param title the value for post_table.title
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post_table.content
     *
     * @return the value of post_table.content
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post_table.content
     *
     * @param content the value for post_table.content
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}