package model;

import java.util.Date;

public class ReplyTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_table.post_id
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_table.username
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_table.floor
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private Short floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_table.time
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply_table.reply_content
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String replyContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_table.post_id
     *
     * @return the value of reply_table.post_id
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_table.post_id
     *
     * @param postId the value for reply_table.post_id
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_table.username
     *
     * @return the value of reply_table.username
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_table.username
     *
     * @param username the value for reply_table.username
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_table.floor
     *
     * @return the value of reply_table.floor
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public Short getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_table.floor
     *
     * @param floor the value for reply_table.floor
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setFloor(Short floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_table.time
     *
     * @return the value of reply_table.time
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_table.time
     *
     * @param time the value for reply_table.time
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply_table.reply_content
     *
     * @return the value of reply_table.reply_content
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply_table.reply_content
     *
     * @param replyContent the value for reply_table.reply_content
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }
}