package model;

public class UserTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.name
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.password
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_table.emil
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    private String emil;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.name
     *
     * @return the value of user_table.name
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.name
     *
     * @param name the value for user_table.name
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.password
     *
     * @return the value of user_table.password
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.password
     *
     * @param password the value for user_table.password
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_table.emil
     *
     * @return the value of user_table.emil
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public String getEmil() {
        return emil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_table.emil
     *
     * @param emil the value for user_table.emil
     *
     * @mbggenerated Tue May 01 14:42:00 CST 2018
     */
    public void setEmil(String emil) {
        this.emil = emil == null ? null : emil.trim();
    }
}